# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myGUI/cvparams.ui'
#
# Created: Sun Jun  3 18:12:15 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_cvparams(object):
    def setupUi(self, cvparams):
        cvparams.setObjectName(_fromUtf8("cvparams"))
        cvparams.resize(534, 257)
        self.layoutWidget = QtGui.QWidget(cvparams)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 518, 239))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.lkp_Table = QtGui.QTableWidget(self.layoutWidget)
        self.lkp_Table.setObjectName(_fromUtf8("lkp_Table"))
        self.lkp_Table.setColumnCount(1)
        self.lkp_Table.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.lkp_Table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.lkp_Table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.lkp_Table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.lkp_Table.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.lkp_Table.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.lkp_Table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.lkp_Table.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.lkp_Table.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.lkp_Table.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.lkp_Table.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.lkp_Table.setItem(4, 0, item)
        self.gridLayout.addWidget(self.lkp_Table, 1, 0, 1, 1)
        self.fp_Table = QtGui.QTableWidget(self.layoutWidget)
        self.fp_Table.setObjectName(_fromUtf8("fp_Table"))
        self.fp_Table.setColumnCount(1)
        self.fp_Table.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        self.fp_Table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.fp_Table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.fp_Table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.fp_Table.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.fp_Table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.fp_Table.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.fp_Table.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.fp_Table.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.fp_Table.setItem(3, 0, item)
        self.gridLayout.addWidget(self.fp_Table, 1, 1, 1, 1)
        self.pushClose = QtGui.QPushButton(self.layoutWidget)
        self.pushClose.setObjectName(_fromUtf8("pushClose"))
        self.gridLayout.addWidget(self.pushClose, 2, 0, 1, 2)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(cvparams)
        QtCore.QMetaObject.connectSlotsByName(cvparams)

    def retranslateUi(self, cvparams):
        cvparams.setWindowTitle(QtGui.QApplication.translate("cvparams", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("cvparams", "feature_params", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lkp_Table.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("cvparams", "winSize", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lkp_Table.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("cvparams", "maxLevel", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lkp_Table.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("cvparams", "Count", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lkp_Table.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("cvparams", "EPS", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lkp_Table.verticalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("cvparams", "derivlam", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.lkp_Table.isSortingEnabled()
        self.lkp_Table.setSortingEnabled(False)
        item = self.lkp_Table.item(0, 0)
        item.setText(QtGui.QApplication.translate("cvparams", "50", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lkp_Table.item(1, 0)
        item.setText(QtGui.QApplication.translate("cvparams", "100", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lkp_Table.item(2, 0)
        item.setText(QtGui.QApplication.translate("cvparams", "50", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lkp_Table.item(3, 0)
        item.setText(QtGui.QApplication.translate("cvparams", "0.1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lkp_Table.item(4, 0)
        item.setText(QtGui.QApplication.translate("cvparams", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.lkp_Table.setSortingEnabled(__sortingEnabled)
        item = self.fp_Table.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("cvparams", "max corners", None, QtGui.QApplication.UnicodeUTF8))
        item = self.fp_Table.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("cvparams", "quality", None, QtGui.QApplication.UnicodeUTF8))
        item = self.fp_Table.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("cvparams", "minDist", None, QtGui.QApplication.UnicodeUTF8))
        item = self.fp_Table.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("cvparams", "block", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.fp_Table.isSortingEnabled()
        self.fp_Table.setSortingEnabled(False)
        item = self.fp_Table.item(0, 0)
        item.setText(QtGui.QApplication.translate("cvparams", "500", None, QtGui.QApplication.UnicodeUTF8))
        item = self.fp_Table.item(1, 0)
        item.setText(QtGui.QApplication.translate("cvparams", "0.001", None, QtGui.QApplication.UnicodeUTF8))
        item = self.fp_Table.item(2, 0)
        item.setText(QtGui.QApplication.translate("cvparams", "7", None, QtGui.QApplication.UnicodeUTF8))
        item = self.fp_Table.item(3, 0)
        item.setText(QtGui.QApplication.translate("cvparams", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.fp_Table.setSortingEnabled(__sortingEnabled)
        self.pushClose.setText(QtGui.QApplication.translate("cvparams", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("cvparams", "lk_params", None, QtGui.QApplication.UnicodeUTF8))

