# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myGUI/mainwindow.ui'
#
# Created: Sun Jun  3 19:28:44 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName(_fromUtf8("mainwindow"))
        mainwindow.setEnabled(True)
        mainwindow.resize(684, 633)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainwindow.sizePolicy().hasHeightForWidth())
        mainwindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtGui.QWidget(mainwindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.video_lbl = QtGui.QLabel(self.centralWidget)
        self.video_lbl.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_lbl.sizePolicy().hasHeightForWidth())
        self.video_lbl.setSizePolicy(sizePolicy)
        self.video_lbl.setMinimumSize(QtCore.QSize(200, 0))
        self.video_lbl.setMaximumSize(QtCore.QSize(400, 16777215))
        self.video_lbl.setAutoFillBackground(True)
        self.video_lbl.setText(_fromUtf8(""))
        self.video_lbl.setObjectName(_fromUtf8("video_lbl"))
        self.gridLayout_3.addWidget(self.video_lbl, 0, 0, 1, 1)
        self.pushStart = QtGui.QPushButton(self.centralWidget)
        self.pushStart.setObjectName(_fromUtf8("pushStart"))
        self.gridLayout_3.addWidget(self.pushStart, 1, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.centralWidget)
        self.splitter.setMinimumSize(QtCore.QSize(200, 0))
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame_qwt1 = QtGui.QFrame(self.splitter)
        self.frame_qwt1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_qwt1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_qwt1.setObjectName(_fromUtf8("frame_qwt1"))
        self.gridLayout = QtGui.QGridLayout(self.frame_qwt1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.qwtPlot1 = Qwt5.QwtPlot(self.frame_qwt1)
        self.qwtPlot1.setObjectName(_fromUtf8("qwtPlot1"))
        self.gridLayout.addWidget(self.qwtPlot1, 0, 0, 1, 1)
        self.frame_qwt2 = QtGui.QFrame(self.splitter)
        self.frame_qwt2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_qwt2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_qwt2.setObjectName(_fromUtf8("frame_qwt2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_qwt2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.qwtPlot2 = Qwt5.QwtPlot(self.frame_qwt2)
        self.qwtPlot2.setObjectName(_fromUtf8("qwtPlot2"))
        self.gridLayout_2.addWidget(self.qwtPlot2, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.splitter, 0, 1, 1, 1)
        self.pausefirstBox = QtGui.QCheckBox(self.centralWidget)
        self.pausefirstBox.setTristate(False)
        self.pausefirstBox.setObjectName(_fromUtf8("pausefirstBox"))
        self.gridLayout_3.addWidget(self.pausefirstBox, 4, 0, 1, 1)
        self.freezeBox = QtGui.QCheckBox(self.centralWidget)
        self.freezeBox.setObjectName(_fromUtf8("freezeBox"))
        self.gridLayout_3.addWidget(self.freezeBox, 3, 0, 1, 1)
        mainwindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(mainwindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 684, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuInput = QtGui.QMenu(self.menuFile)
        self.menuInput.setObjectName(_fromUtf8("menuInput"))
        self.menuAbout = QtGui.QMenu(self.menuBar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuTools = QtGui.QMenu(self.menuBar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuPlot = QtGui.QMenu(self.menuBar)
        self.menuPlot.setObjectName(_fromUtf8("menuPlot"))
        self.menuPlot1 = QtGui.QMenu(self.menuPlot)
        self.menuPlot1.setObjectName(_fromUtf8("menuPlot1"))
        self.menuX_axis = QtGui.QMenu(self.menuPlot1)
        self.menuX_axis.setObjectName(_fromUtf8("menuX_axis"))
        self.menuY_axis = QtGui.QMenu(self.menuPlot1)
        self.menuY_axis.setObjectName(_fromUtf8("menuY_axis"))
        self.menuPlot2 = QtGui.QMenu(self.menuPlot)
        self.menuPlot2.setObjectName(_fromUtf8("menuPlot2"))
        self.menuX_axis_2 = QtGui.QMenu(self.menuPlot2)
        self.menuX_axis_2.setObjectName(_fromUtf8("menuX_axis_2"))
        self.menuY_axis_2 = QtGui.QMenu(self.menuPlot2)
        self.menuY_axis_2.setObjectName(_fromUtf8("menuY_axis_2"))
        mainwindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(mainwindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        mainwindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(mainwindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        mainwindow.setStatusBar(self.statusBar)
        self.actionFile = QtGui.QAction(mainwindow)
        self.actionFile.setEnabled(True)
        self.actionFile.setObjectName(_fromUtf8("actionFile"))
        self.actionCam = QtGui.QAction(mainwindow)
        self.actionCam.setObjectName(_fromUtf8("actionCam"))
        self.actionQuit = QtGui.QAction(mainwindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionTracking = QtGui.QAction(mainwindow)
        self.actionTracking.setObjectName(_fromUtf8("actionTracking"))
        self.actionPlot3 = QtGui.QAction(mainwindow)
        self.actionPlot3.setObjectName(_fromUtf8("actionPlot3"))
        self.actionTime = QtGui.QAction(mainwindow)
        self.actionTime.setObjectName(_fromUtf8("actionTime"))
        self.actionAmp = QtGui.QAction(mainwindow)
        self.actionAmp.setObjectName(_fromUtf8("actionAmp"))
        self.actionD_amp_dt = QtGui.QAction(mainwindow)
        self.actionD_amp_dt.setObjectName(_fromUtf8("actionD_amp_dt"))
        self.actionTheta = QtGui.QAction(mainwindow)
        self.actionTheta.setObjectName(_fromUtf8("actionTheta"))
        self.actionD_theta_dt = QtGui.QAction(mainwindow)
        self.actionD_theta_dt.setObjectName(_fromUtf8("actionD_theta_dt"))
        self.actionX = QtGui.QAction(mainwindow)
        self.actionX.setObjectName(_fromUtf8("actionX"))
        self.actionY = QtGui.QAction(mainwindow)
        self.actionY.setObjectName(_fromUtf8("actionY"))
        self.actionTime_2 = QtGui.QAction(mainwindow)
        self.actionTime_2.setObjectName(_fromUtf8("actionTime_2"))
        self.actionAmp_2 = QtGui.QAction(mainwindow)
        self.actionAmp_2.setObjectName(_fromUtf8("actionAmp_2"))
        self.actionD_amp_dt_2 = QtGui.QAction(mainwindow)
        self.actionD_amp_dt_2.setObjectName(_fromUtf8("actionD_amp_dt_2"))
        self.actionTheta_2 = QtGui.QAction(mainwindow)
        self.actionTheta_2.setObjectName(_fromUtf8("actionTheta_2"))
        self.actionD_theta_dt_2 = QtGui.QAction(mainwindow)
        self.actionD_theta_dt_2.setObjectName(_fromUtf8("actionD_theta_dt_2"))
        self.actionX_2 = QtGui.QAction(mainwindow)
        self.actionX_2.setObjectName(_fromUtf8("actionX_2"))
        self.actionY_2 = QtGui.QAction(mainwindow)
        self.actionY_2.setObjectName(_fromUtf8("actionY_2"))
        self.actionTime_3 = QtGui.QAction(mainwindow)
        self.actionTime_3.setObjectName(_fromUtf8("actionTime_3"))
        self.actionAmp_3 = QtGui.QAction(mainwindow)
        self.actionAmp_3.setObjectName(_fromUtf8("actionAmp_3"))
        self.actionD_amp_dt_3 = QtGui.QAction(mainwindow)
        self.actionD_amp_dt_3.setObjectName(_fromUtf8("actionD_amp_dt_3"))
        self.actionTheta_3 = QtGui.QAction(mainwindow)
        self.actionTheta_3.setObjectName(_fromUtf8("actionTheta_3"))
        self.actionD_theta_dt_3 = QtGui.QAction(mainwindow)
        self.actionD_theta_dt_3.setObjectName(_fromUtf8("actionD_theta_dt_3"))
        self.actionX_3 = QtGui.QAction(mainwindow)
        self.actionX_3.setObjectName(_fromUtf8("actionX_3"))
        self.actionY_3 = QtGui.QAction(mainwindow)
        self.actionY_3.setObjectName(_fromUtf8("actionY_3"))
        self.actionTime_4 = QtGui.QAction(mainwindow)
        self.actionTime_4.setObjectName(_fromUtf8("actionTime_4"))
        self.actionAmp_4 = QtGui.QAction(mainwindow)
        self.actionAmp_4.setObjectName(_fromUtf8("actionAmp_4"))
        self.actionD_amp_dt_4 = QtGui.QAction(mainwindow)
        self.actionD_amp_dt_4.setObjectName(_fromUtf8("actionD_amp_dt_4"))
        self.actionTheta_4 = QtGui.QAction(mainwindow)
        self.actionTheta_4.setObjectName(_fromUtf8("actionTheta_4"))
        self.actionD_theta_dt_4 = QtGui.QAction(mainwindow)
        self.actionD_theta_dt_4.setObjectName(_fromUtf8("actionD_theta_dt_4"))
        self.actionX_4 = QtGui.QAction(mainwindow)
        self.actionX_4.setObjectName(_fromUtf8("actionX_4"))
        self.actionY_4 = QtGui.QAction(mainwindow)
        self.actionY_4.setObjectName(_fromUtf8("actionY_4"))
        self.actionRemove = QtGui.QAction(mainwindow)
        self.actionRemove.setObjectName(_fromUtf8("actionRemove"))
        self.actionUpdate = QtGui.QAction(mainwindow)
        self.actionUpdate.setObjectName(_fromUtf8("actionUpdate"))
        self.actionSave = QtGui.QAction(mainwindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.menuInput.addAction(self.actionFile)
        self.menuInput.addAction(self.actionCam)
        self.menuFile.addAction(self.menuInput.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionQuit)
        self.menuTools.addAction(self.actionTracking)
        self.menuTools.addAction(self.actionUpdate)
        self.menuX_axis.addAction(self.actionTime)
        self.menuX_axis.addAction(self.actionAmp)
        self.menuX_axis.addAction(self.actionD_amp_dt)
        self.menuX_axis.addAction(self.actionTheta)
        self.menuX_axis.addAction(self.actionD_theta_dt)
        self.menuX_axis.addAction(self.actionX)
        self.menuX_axis.addAction(self.actionY)
        self.menuY_axis.addAction(self.actionTime_2)
        self.menuY_axis.addAction(self.actionAmp_2)
        self.menuY_axis.addAction(self.actionD_amp_dt_2)
        self.menuY_axis.addAction(self.actionTheta_2)
        self.menuY_axis.addAction(self.actionD_theta_dt_2)
        self.menuY_axis.addAction(self.actionX_2)
        self.menuY_axis.addAction(self.actionY_2)
        self.menuPlot1.addAction(self.menuX_axis.menuAction())
        self.menuPlot1.addAction(self.menuY_axis.menuAction())
        self.menuX_axis_2.addAction(self.actionTime_3)
        self.menuX_axis_2.addAction(self.actionAmp_3)
        self.menuX_axis_2.addAction(self.actionD_amp_dt_3)
        self.menuX_axis_2.addAction(self.actionTheta_3)
        self.menuX_axis_2.addAction(self.actionD_theta_dt_3)
        self.menuX_axis_2.addAction(self.actionX_3)
        self.menuX_axis_2.addAction(self.actionY_3)
        self.menuY_axis_2.addAction(self.actionTime_4)
        self.menuY_axis_2.addAction(self.actionAmp_4)
        self.menuY_axis_2.addAction(self.actionD_amp_dt_4)
        self.menuY_axis_2.addAction(self.actionTheta_4)
        self.menuY_axis_2.addAction(self.actionD_theta_dt_4)
        self.menuY_axis_2.addAction(self.actionX_4)
        self.menuY_axis_2.addAction(self.actionY_4)
        self.menuPlot2.addAction(self.menuX_axis_2.menuAction())
        self.menuPlot2.addAction(self.menuY_axis_2.menuAction())
        self.menuPlot2.addAction(self.actionRemove)
        self.menuPlot.addAction(self.menuPlot1.menuAction())
        self.menuPlot.addAction(self.menuPlot2.menuAction())
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuPlot.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        mainwindow.setWindowTitle(QtGui.QApplication.translate("mainwindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.pushStart.setText(QtGui.QApplication.translate("mainwindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.pausefirstBox.setText(QtGui.QApplication.translate("mainwindow", "Pause first frame in motion mode", None, QtGui.QApplication.UnicodeUTF8))
        self.freezeBox.setText(QtGui.QApplication.translate("mainwindow", "Freeze mode ", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("mainwindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInput.setTitle(QtGui.QApplication.translate("mainwindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("mainwindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("mainwindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlot.setTitle(QtGui.QApplication.translate("mainwindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlot1.setTitle(QtGui.QApplication.translate("mainwindow", "Plot1", None, QtGui.QApplication.UnicodeUTF8))
        self.menuX_axis.setTitle(QtGui.QApplication.translate("mainwindow", "x-axis", None, QtGui.QApplication.UnicodeUTF8))
        self.menuY_axis.setTitle(QtGui.QApplication.translate("mainwindow", "y-axis", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlot2.setTitle(QtGui.QApplication.translate("mainwindow", "Plot2", None, QtGui.QApplication.UnicodeUTF8))
        self.menuX_axis_2.setTitle(QtGui.QApplication.translate("mainwindow", "x-axis", None, QtGui.QApplication.UnicodeUTF8))
        self.menuY_axis_2.setTitle(QtGui.QApplication.translate("mainwindow", "y-axis", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFile.setText(QtGui.QApplication.translate("mainwindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFile.setShortcut(QtGui.QApplication.translate("mainwindow", "Meta+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCam.setText(QtGui.QApplication.translate("mainwindow", "Cam", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCam.setShortcut(QtGui.QApplication.translate("mainwindow", "Meta+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("mainwindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("mainwindow", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTracking.setText(QtGui.QApplication.translate("mainwindow", "Tracking", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlot3.setText(QtGui.QApplication.translate("mainwindow", "Plot3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTime.setText(QtGui.QApplication.translate("mainwindow", "time", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAmp.setText(QtGui.QApplication.translate("mainwindow", "amp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionD_amp_dt.setText(QtGui.QApplication.translate("mainwindow", "d(amp)/dt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTheta.setText(QtGui.QApplication.translate("mainwindow", "theta", None, QtGui.QApplication.UnicodeUTF8))
        self.actionD_theta_dt.setText(QtGui.QApplication.translate("mainwindow", "d(theta)/dt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionX.setText(QtGui.QApplication.translate("mainwindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.actionY.setText(QtGui.QApplication.translate("mainwindow", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTime_2.setText(QtGui.QApplication.translate("mainwindow", "time", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAmp_2.setText(QtGui.QApplication.translate("mainwindow", "amp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionD_amp_dt_2.setText(QtGui.QApplication.translate("mainwindow", "d(amp)/dt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTheta_2.setText(QtGui.QApplication.translate("mainwindow", "theta", None, QtGui.QApplication.UnicodeUTF8))
        self.actionD_theta_dt_2.setText(QtGui.QApplication.translate("mainwindow", "d(theta)/dt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionX_2.setText(QtGui.QApplication.translate("mainwindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.actionY_2.setText(QtGui.QApplication.translate("mainwindow", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTime_3.setText(QtGui.QApplication.translate("mainwindow", "time", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAmp_3.setText(QtGui.QApplication.translate("mainwindow", "amp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionD_amp_dt_3.setText(QtGui.QApplication.translate("mainwindow", "d(amp)/dt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTheta_3.setText(QtGui.QApplication.translate("mainwindow", "theta", None, QtGui.QApplication.UnicodeUTF8))
        self.actionD_theta_dt_3.setText(QtGui.QApplication.translate("mainwindow", "d(theta)/dt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionX_3.setText(QtGui.QApplication.translate("mainwindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.actionY_3.setText(QtGui.QApplication.translate("mainwindow", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTime_4.setText(QtGui.QApplication.translate("mainwindow", "time", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAmp_4.setText(QtGui.QApplication.translate("mainwindow", "amp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionD_amp_dt_4.setText(QtGui.QApplication.translate("mainwindow", "d(amp)/dt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTheta_4.setText(QtGui.QApplication.translate("mainwindow", "theta", None, QtGui.QApplication.UnicodeUTF8))
        self.actionD_theta_dt_4.setText(QtGui.QApplication.translate("mainwindow", "d(theta)/dt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionX_4.setText(QtGui.QApplication.translate("mainwindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.actionY_4.setText(QtGui.QApplication.translate("mainwindow", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove.setText(QtGui.QApplication.translate("mainwindow", "remove", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate.setText(QtGui.QApplication.translate("mainwindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("mainwindow", "Save", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qwt5
